apiVersion: v1
kind: Service
metadata:
  name: go-catalog
  namespace: demo
  labels:
    app: go-catalog
spec:
  type: ClusterIP
  selector:
    app: go-catalog
  ports:
    - port: 8081
      targetPort: 8081
